Repository wijohnst/thriving-park-documentation, pull requests merged in 2022-03, with the labels that each got.

#7 Issue #6 - Remove boilerplate
  blog/03-20-2022-first-blog-post.mdx
  blog/2019-05-28-first-blog-post.md
  blog/2019-05-29-long-blog-post.md
  blog/2021-08-01-mdx-blog-post.mdx
  blog/2021-08-26-welcome/docusaurus-plushie-banner.jpeg
  blog/2021-08-26-welcome/index.md
  blog/authors.yml
  docs/index.md
  docs/intro.md
  docs/tutorial-basics/_category_.json
  docs/tutorial-basics/congratulations.md
  docs/tutorial-basics/create-a-blog-post.md
  docs/tutorial-basics/create-a-document.md
  docs/tutorial-basics/create-a-page.md
  docs/tutorial-basics/deploy-your-site.md
  docs/tutorial-basics/markdown-features.mdx
  docs/tutorial-extras/_category_.json
  docs/tutorial-extras/manage-docs-versions.md
  docs/tutorial-extras/translate-your-site.md
  docusaurus.config.js
  src/pages/index.js
  static/img/favicon.ico
  static/img/logo.svg
Labels: documentation, docusaurus 🦎

#9 Issue 8 - Base Styling
  src/css/custom.css
Labels: documentation, docusaurus 🦎

#12 Issue 11 - Add ParkSign Component
  src/components/ParkSign/ParkSign.jsx
  src/components/ParkSign/styles.module.css
  src/css/custom.css
  src/pages/index.js
Labels: documentation, docusaurus 🦎

#17 Task: Add FAQLayout component - issue #15
  src/components/FAQLayout/FAQLayout.jsx
  src/components/FAQLayout/styles.modules.css
Labels: enhancement, docusaurus 🦎

#16 FAQ component
  src/components/FAQ/FAQ.jsx
  src/components/FAQ/styles.module.css
Labels: enhancement, docusaurus 🦎

#20 Issue 19 - Project Overview section
  blog/03-27-2022-weekly-update-1.mdx
  docs/Project Overview/DrivingPark.md
  docs/Project Overview/NeighborhoodOperatingSystem.md
  docs/Project Overview/StandingDevTeamSimulation.md
  docs/Project Overview/ThrivingPark.md
  docs/index.md
  docusaurus.config.js
  static/img/DP_Map.svg
Labels: documentation, enhancement, docusaurus 🦎

#26 Task/issue 24 add use media query
  docs/Docs Repo/Custom Hooks/useMediaQuery.mdx
  src/components/ParkSign/ParkSign.jsx
  src/hooks/useMediaQuery.ts
  src/utils/constants.js
Labels: documentation, enhancement, docusaurus 🦎

#25 DOCS: Table component
  src/components/Table/Table.jsx
  src/components/Table/styles.module.css
Labels: enhancement, docusaurus 🦎
